name: Bug Report
description: Create a report to help us improve
title: ""
labels: ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea #description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea #reproduce
    attributes:
      label: Environment
      description: The OS + version you’re running Kubescape on, e.g Ubuntu 22.04 LTS
Version: the version that Kubescape reports when you run `kubescape version`
      placeholder: Kindly elaborate.

  - type: dropdown #urgent
    attributes:
      label: Urgency (Optional)
      description: How urgent do you think it is to fix this bug?
      options:
        - Low priority
        - Medium priority
        - High priority
